# Generated by Django 2.2.6 on 2020-01-29 16:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Edit the content you want to see before the form.'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Set the message users will see after submitting the form.'),
        ),
    ]
