# Generated by Django 2.2.6 on 2020-01-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendSMS',
        ),
    ]
