# Generated by Django 2.2.6 on 2019-12-27 18:38

import base.models
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.core.fields.StreamField([('html', base.models.RawHTMLBlock())])),
            ],
        ),
    ]
