# Generated by Django 2.2.6 on 2019-12-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rawhtml_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rawhtml',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.RawHtml'),
        ),
    ]
