# Generated by Django 2.2.6 on 2019-12-27 21:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_homepage_rawhtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='rawhtml',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='rawhtml',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.RawHtml', verbose_name='Add Snippet'),
        ),
        migrations.AlterField(
            model_name='rawhtml',
            name='text',
            field=wagtail.core.fields.StreamField([('html', wagtail.core.blocks.RawHTMLBlock())], verbose_name='Add Snippet'),
        ),
    ]
