# Generated by Django 2.2.6 on 2020-01-06 14:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200105_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='body',
        ),
        migrations.AddField(
            model_name='footertext',
            name='text',
            field=wagtail.core.fields.StreamField([('html', wagtail.core.blocks.RawHTMLBlock())], null=True, verbose_name='Add Snippet'),
        ),
    ]
