# Generated by Django 2.2.6 on 2020-01-08 17:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200108_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='body',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock(help_text='This will set the background image of the row.', required=False))]))], blank=True, verbose_name='Page body'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock(help_text='This will set the background image of the row.', required=False))]))], blank=True, verbose_name='Page body'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock(help_text='This will set the background image of the row.', required=False))]))], blank=True, verbose_name='Page body'),
        ),
    ]
