# Generated by Django 2.2.6 on 2020-01-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20200121_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='search_image',
        ),
    ]
