# Generated by Django 2.2.6 on 2020-02-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20200124_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='rawhtml',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.RawHtml', verbose_name='Add Snippet'),
        ),
    ]
